### PR TITLE
Features To Support Spam Mitigation & Cleanup

### PR DESCRIPTION
**Pull request by nfraker**
This is a combination of two features, with the goal of cutting down on the number of bots showing up in comments on public decks.

- Creates a reCaptcha v2 requirement on the registration form that must be passed to successfully register. [Example of CAPTCHA on page](http://i.imgur.com/iWlHVEI.png)
- Adds the ability to _soft_ delete (they won't show up on the site after deletion but are still in the DB, in case someone's being an ass but trying to delete the evidence) comments on public decks. The permissions to delete work as follows:
    - If you are the comment poster, you can delete your own comment but no others.
    - If you are the deck creator, you can delete any comments.
    - If you are an administrator, you can delete any comments.

[Example of the delete option being present](http://i.imgur.com/0O5hywg.png)
[Example of the delete option being absent](http://imgur.com/vMb4xxJ.png)

There are some steps you'd need to perform to set up the CAPTCHA:
1. In `.env.example` you'll see two new environment variables that need to be in production's .env, named [NOCAPTCHA_SITEKEY and NOCAPTCHA_SECRET](https://github.com/nfraker/FFTCGDB/blob/PROJECT-spam-cleanup/.env.example#L14). These are API creds you can generate at https://www.google.com/recaptcha/admin#list
    1. You'll want to sign up for a ReCAPTCHA v2 key for the domain 'fftcgdb.com', then take the "site key" and 'secret' and paste it into your .env as they're presented on the site, e.g.:

        >`NOCAPTCHA_SITEKEY=abcdefghijklmnopqrstuvwxyz`
        >`NOCAPTCHA_SECRET=1234567890`
2. You'll also need to run `composer update`, because I'm using anhskohbo/no-captcha v2.3 to handle the API request & response and that's a new dependency.

If your config/app.php deviates a lot from what's in the repo, you may be better off just adding the `Anhskohbo\NoCaptcha\NoCaptchaServiceProvider::class` entry to the bottom of the Application Service Providers list. Otherwise, I've included that change in this PR.

-----

After all this is installed we should see a marked decrease in the number of annoying comments (for example, 11 of the 15 comments on http://fftcgdb.com/d/3841 are all spam from bots). Plus, people will be able to go in and clean up their own comments if they're trying to have productive discussions.

### CODE REVIEW

**Comment by nfraker** [comment]
There is one outstanding bug with this that I unfortunately cannot figure out, because of my lack of familiarity with Laravel, and maybe you would be able to take care of it - If you attempt to submit for registration without passing the captcha, it causes a 500 error and takes you to the sadmog error page. I've done all the things people have said would be required to get the validator to display the "captcha required" message, but it doesn't work for me and I'm not sure why.

**Comment by nfraker** [comment]
@danives I checked the site and the captcha widget isn't showing up. If `composer update` didn't install the missing module you may need to do `composer install`.

**Comment by nfraker** [comment]
@danives it also looks like production is missing the new style entry in public/css/style.css because the delete comment button is a button, not a link.

**Comment by HandsomeStrife** [comment]
I think the captcha wasn't working because I hadn't set up the captcha site/secret keys in the .env file, which I've now done (completely spaced it). Also I've incremented the styles.css version so hopefully that'll pull through the latest stylings now.

**Pull request merged**
